apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-project-config
  namespace: project
data:
  PORT: "3000"
  BACKEND_URL: "http://todo-backend-svc.project:3000"
  IMAGE_URL: "https://picsum.photos/1200"
  IMAGE_UPDATE_INTERVAL: "600000"
