apiVersion: v1
kind: Service
metadata:
  name: todo-app-svc
spec:
  type: NodePort
  selector:
    app: todo-app
  ports:
    - nodePort: 30080
      port: 3000
      targetPort: 3000
      protocol: TCP
